version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    labels:
      worklet.service: "postgres"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    labels:
      worklet.service: "redis"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    labels:
      worklet.service: "web"